### PR TITLE
Restores binding to specific interface

### PR DESCRIPTION
**Pull request by kirichkov**
After the recent updates and the addition of new features my previous changes were incomplete. This tries to restore them. I've tested my changes with the Hub's light, motion sensor and temperature sensor.

### CODE REVIEW

**Comment by kirichkov** [comment]
@jmvermeulen can you test whether this works with Windows 10, if it doesn't please give me some feedback and I'll try to get this working on both Linux and Windows. 

It'd be helpful if someone tests this on OS X as well.

**Comment by tam-wh** [comment]
Anyone else tested this? If there's no big issue I'll merge

**Comment by DuckY1987** [comment]
\o/ you fixed my issue: raspberry pi 3 / raspbian works!

**Comment by tam-wh** [comment]
You have to define interface in xiaomi option when running HA with raspberry pi?

**Comment by dev-goalz** [comment]
@kirichkov confirmed this to be working on Windows 10.

But I'm a little confused, since this [commit ](https://github.com/lazcad/homeassistant/commit/b97b8a59f054be54e9edf7453bdefba3d94cf91c) I didn't have problems anymore on specifying the interface at Windows 10.

Are this changes still required/better?

Edit: looking at the code, this maybe fixes a **non**-Windows situation? Since this Windows implementation is doing the same thing as before, right?

**Comment by DuckY1987** [comment]
@ravetam  Seem to be, i have multiple interfaces (eth0 and wlan0)

I didn't get it working without the interface option, neither with blank SID nor with filled one.

A friend told me he has exactly the same setup besides hardware and it worked well, he runs hass on vmware.

**Comment by tam-wh** [comment]
If this fixes both raspberry pi and windows i guess this should be fine. I'll go ahead and merge the code. Thanks @kirichkov !

**Comment by kirichkov** [comment]
The discovery now has platform-specific workarounds so it's not exactly the same code as before.
I treat non-windows platforms the same, so it's possible macOS exhibits issues. When someone provides feedback for macOS issues I can look at it.

@jmvermeulen the commit you are referring to broke discovery on ubuntu (very likely also raspbian) and made it work on Windows. The platform-specific workaround should resolve this and the code now should be working for both windows and Linux, and hopefully macOS.

**Pull request merged**
