### PR TITLE
Add aqara curtain support

### PR DESCRIPTION
**Pull request by SchumyHao**
Hi
I did some job about curtain support.

I tested and worked well. Hope this can merged in.

### CODE REVIEW

**Comment by syssi** [comment]
Can you make a pull request for github.com/danielhiversen/homeassistant, too? Thanks a lot!

**Comment by moskovskiy82** [comment]
Yes please create a pull to danielhiversen!

**Comment by SchumyHao** [comment]
I made a pull request to daniehiversen

But why you are using this repo? Why not Lazcad?

**Comment by syssi** [comment]
You have done a good job by filling the gap between the two repositories with PR #41. I think there still some differences.

**Comment by moskovskiy82** [comment]
SchumyHao, just look at the dates of other pull requests submitted to lazcad HA rep. Not merged yet...

**Pull request closed without merging**
